### ISSUE TITLE
Is it possible to merge this fork to upstream vcglib?

### ISSUE THREAD

**Issue by kevinsmia1939** [cdcseacave/VCG#1]
Hello,

I am trying to package openMVS for openSUSE and other rpm based distros.
I was able to package openMVG, and I would like openMVS too.

I noticed that I need to use this fork of vcglib to compile openMVS successfully.

Ideally, it would be better to use the upstream vcglib, because it would be better if the dependency is only vcglib and not other fork.
I guess that this fork fix some bugs and modified vcglib that the upstream would not accept?

I noticed that upstream vcglib has a new version 2020.09. So I tried it, but still run into similarly reported issue in the past.

```
/home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/MVS/Mesh.cpp: In member function 'void MVS::Mesh::Clean(float, float, bool, unsigned int, unsigned int, bool)':
/home/abuild/rpmbuild/BUILD/openMVS-1.1.1/libs/MVS/Mesh.cpp:1000:6: error: 'class vcg::tri::TriEdgeCollapseQuadricParameter' has no member named 'BoundaryWeight'
1000 |   pp.BoundaryWeight = 1; // the importance of the boundary during simplification: the value is in the range (0..+inf), default (1.0) means that the boundary has the same importance as the rest; values greater than 1.0 raise boundary importance and has the effect of removing less vertices on the border
```
Would it be possible to merge this fork with the upstream vcglib? 

My attempted to build openMVS with vcglib 2020.09.
https://build.opensuse.org/package/live_build_log/home:andythe_great/openMVS/openSUSE_Tumbleweed/x86_64

**Comment by cdcseacave** [comment]
pls use my fork, as that is tested to work as desired; vcglib changes frequently and not always for the best; I'll update my fork when necessary and make sure OpenMVS compiles.

**Comment by cdcseacave** [comment]
the alternative is to make OpenMVS compile with latest vcglib and make sure everything works and is stable, and make a PR for me to update O[enMVS

**Comment by kevinsmia1939** [comment]
> the alternative is to make OpenMVS compile with latest vcglib and make sure everything works and is stable, and make a PR for me to update O[enMVS

Thanks for suggestions, I think making openMVS work with latest vcglib would be the best outcome, but C++ is not my area of expertise, do you have some hints on why openMVS failed on latest vcglib? I will look into it more.

**Comment by kevinsmia1939** [comment]
I will just bundle VCG into openMVS.
