### ISSUE TITLE
no return value error/warning in isotropic_remeshing.h

### ISSUE THREAD

**Issue by CanCanZeng** [cdcseacave/VCG#2]
Hi @cdcseacave , I run into a compilation problem for OpenMVS2.0 on ubuntu20.04 with GCC9.4. It's about the `chooseBestCrossCollapse` function in `vcglib/vcg/complex/algorithms/isotropic_remeshing.h` line 1038. The function is declared as bool but without any return value. Although it can be fix by setting compilation flag, I think it's better to fix this warning/error directly in VCG. Can you update this repo?

**Comment by cdcseacave** [comment]
thx, fixed in the last commit
